version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword       # MySQL root password
      MYSQL_DATABASE: bookapi                 # Database name (DB_DATABASE)
      MYSQL_USER: app                          # MySQL username (DB_USERNAME)
      MYSQL_PASSWORD: password                # MySQL password (DB_PASSWORD)
    ports:
      - "3306:3306"                            # Expose MySQL on port 3306
    volumes:
      - mysql_data:/var/lib/mysql             # Persistent storage for MySQL data
    networks:
      - app-network                           # Connects to the custom network

  api:
    build:
      context: ./api              # Directory with Dockerfile for Laravel app
      dockerfile: Dockerfile                 # Ensure Dockerfile is named correctly if not the default
    container_name: laravel-app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    depends_on:
      - db                                    # Ensure db starts first
    ports:
      - "8000:8000"                               # Expose Laravel app on port 8000
    networks:
      - app-network                           # Connect to the same network as MySQL
     
  frontend:
    build:
      context: ./client 
      dockerfile: Dockerfile   # Use Dockerfile from the client directory
    container_name: frontend
    ports:
      - "3000:3000"                  # Expose port 3000 to the host
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://api:8000          # Set environment to production
                      
volumes:
  mysql_data:
    driver: local                             # Persistent MySQL data

networks:
  app-network:
    driver: bridge                            # Custom network for communication
